name: Run Unit Tests

on:
  push:
    branches:
      - main  # Change this to the default branch of your repository

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Replace with the path to your requirements file

    - name: Run Unit Tests
      run: |
        python -m pytest  # Replace with the command to run your tests
